import {
  FileText,
  Rocket,
  User,
  Hourglass,
  Flag,
  CheckCircle2,
  StopCircle,
  HelpCircle,
} from "lucide-react";
import React from "react";

export enum TransactionTypeName {
  BlockMetadata = "block_metadata_transaction",
  Genesis = "genesis_transaction",
  User = "user_transaction",
  Pending = "pending_transaction",
  StateCheckpoint = "state_checkpoint_transaction",
  Validator = "validator_transaction",
  BlockEpilogue = "block_epilogue_transaction",
  Unknown = "unknown",
}

export const TRANSACTION_TYPE_INFO: Record<
  TransactionTypeName,
  { label: string; description: string; icon: React.ReactNode }
> = {
  [TransactionTypeName.BlockMetadata]: {
    label: "Block Metadata",
    description:
      "System-generated transactions that provide additional data for each confirmed block.",
    icon: <FileText className="h-5 w-5" />,
  },
  [TransactionTypeName.Genesis]: {
    label: "Genesis Transaction",
    description: "The first transaction in the Movement blockchain.",
    icon: <Rocket className="h-5 w-5" />,
  },
  [TransactionTypeName.User]: {
    label: "User Transaction",
    description: "A transaction generated by users of the Movement blockchain.",
    icon: <User className="h-5 w-5" />,
  },
  [TransactionTypeName.Pending]: {
    label: "Pending Transaction",
    description:
      "A transaction currently in the mempool waiting to be committed.",
    icon: <Hourglass className="h-5 w-5" />,
  },
  [TransactionTypeName.StateCheckpoint]: {
    label: "State Checkpoint",
    description:
      "System-generated transactions that save the latest state of the Movement blockchain.",
    icon: <Flag className="h-5 w-5" />,
  },
  [TransactionTypeName.Validator]: {
    label: "Validator Transaction",
    description: "Validator metadata transactions.",
    icon: <CheckCircle2 className="h-5 w-5" />,
  },
  [TransactionTypeName.BlockEpilogue]: {
    label: "Block Epilogue Transaction",
    description: "Block epilogue transactions describing end state of a block.",
    icon: <StopCircle className="h-5 w-5" />,
  },
  [TransactionTypeName.Unknown]: {
    label: "Unknown",
    description: "Unknown transaction type.",
    icon: <HelpCircle className="h-5 w-5" />,
  },
};
