"use client";

import PageNavigation from "@/components/layout/PageNavigation";
import { PageContainer } from "@/components/layout";
import { useGetBlockByHeight } from "@/hooks/blocks/useGetBlock";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import {
  StyledTable,
  StyledTableHeader,
  StyledTableHeaderRow,
  StyledTableHead,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { EnhancedSkeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CopyableAddress } from "@/components/common/CopyableAddress";
import {
  isBlockMetadataTransactionResponse,
  BlockMetadataTransactionResponse,
} from "@aptos-labs/ts-sdk";
import {
  Copy,
  Check,
  BarChart3,
  FileText,
  Info,
  Rocket,
  User,
  Hourglass,
  Flag,
  CheckCircle2,
  StopCircle,
  HelpCircle,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useState, useEffect } from "react";

function formatTimestamp(timestamp: string): string {
  const date = new Date(parseInt(timestamp) / 1000);
  return date.toLocaleString();
}

function CopyableTimestamp({ timestamp }: { timestamp: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(timestamp);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex items-center gap-2">
      <span className="font-mono">{formatTimestamp(timestamp)}</span>
      <button
        onClick={handleCopy}
        className="p-1 hover:bg-muted rounded transition-colors"
        title="Copy timestamp"
      >
        {copied ? (
          <Check className="h-4 w-4 text-guild-green-500" />
        ) : (
          <Copy className="h-4 w-4 text-muted-foreground" />
        )}
      </button>
    </div>
  );
}

// Transaction Type definitions
enum TransactionTypeName {
  BlockMetadata = "block_metadata_transaction",
  Genesis = "genesis_transaction",
  User = "user_transaction",
  Pending = "pending_transaction",
  StateCheckpoint = "state_checkpoint_transaction",
  Validator = "validator_transaction",
  BlockEpilogue = "block_epilogue_transaction",
  Unknown = "unknown",
}

const TRANSACTION_TYPE_INFO: Record<
  TransactionTypeName,
  { label: string; description: string; icon: React.ReactNode }
> = {
  [TransactionTypeName.BlockMetadata]: {
    label: "Block Metadata",
    description:
      "System-generated transactions that provide additional data for each confirmed block.",
    icon: <FileText className="h-5 w-5" />,
  },
  [TransactionTypeName.Genesis]: {
    label: "Genesis Transaction",
    description: "The first transaction in the Movement blockchain.",
    icon: <Rocket className="h-5 w-5" />,
  },
  [TransactionTypeName.User]: {
    label: "User Transaction",
    description: "A transaction generated by users of the Movement blockchain.",
    icon: <User className="h-5 w-5" />,
  },
  [TransactionTypeName.Pending]: {
    label: "Pending Transaction",
    description:
      "A transaction currently in the mempool waiting to be committed.",
    icon: <Hourglass className="h-5 w-5" />,
  },
  [TransactionTypeName.StateCheckpoint]: {
    label: "State Checkpoint",
    description:
      "System-generated transactions that save the latest state of the Movement blockchain.",
    icon: <Flag className="h-5 w-5" />,
  },
  [TransactionTypeName.Validator]: {
    label: "Validator Transaction",
    description: "Validator metadata transactions.",
    icon: <CheckCircle2 className="h-5 w-5" />,
  },
  [TransactionTypeName.BlockEpilogue]: {
    label: "Block Epilogue Transaction",
    description: "Block epilogue transactions describing end state of a block.",
    icon: <StopCircle className="h-5 w-5" />,
  },
  [TransactionTypeName.Unknown]: {
    label: "Unknown",
    description: "Unknown transaction type.",
    icon: <HelpCircle className="h-5 w-5" />,
  },
};

function getTransactionTypeLabel(type: string): string {
  const info =
    TRANSACTION_TYPE_INFO[type as TransactionTypeName] ??
    TRANSACTION_TYPE_INFO[TransactionTypeName.Unknown];
  return info.label;
}

function TransactionTypeTooltip() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="p-0.5 hover:bg-muted rounded transition-colors ml-1"
        title="View transaction types"
      >
        <Info className="h-4 w-4 text-muted-foreground" />
      </button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Transaction Types</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 max-h-[60vh] overflow-y-auto">
            {Object.values(TransactionTypeName).map((type) => {
              const info = TRANSACTION_TYPE_INFO[type];
              return (
                <div key={type} className="flex items-start gap-3">
                  <span className="text-muted-foreground mt-0.5">
                    {info.icon}
                  </span>
                  <div className="space-y-1">
                    <p className="font-medium text-sm">{info.label}</p>
                    <p className="text-xs text-muted-foreground">
                      {info.description}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

interface ContentRowProps {
  title: string;
  value: React.ReactNode;
}

function ContentRow({ title, value }: ContentRowProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-[200px_1fr] gap-2 py-3 border-b border-border/50 last:border-b-0">
      <div className="text-sm text-muted-foreground">{title}</div>
      <div className="text-sm">{value ?? "-"}</div>
    </div>
  );
}

export default function BlockDetailPage() {
  const params = useParams();
  const router = useRouter();
  const height = parseInt(params.height as string);
  const tabSlug = params.tab as string[] | undefined;
  const initialTab = tabSlug ? tabSlug[0] : "overview";

  const [currentTab, setCurrentTab] = useState(initialTab);

  const handleTabChange = (value: string) => {
    setCurrentTab(value);
    router.push(`/block/${height}/${value}`);
  };

  useEffect(() => {
    if (tabSlug && tabSlug[0] !== currentTab) {
      setCurrentTab(tabSlug[0]);
    }
  }, [tabSlug]);

  const {
    data: block,
    isLoading,
    error,
  } = useGetBlockByHeight({
    height,
    withTransactions: true,
  });

  if (isLoading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="space-y-4">
          <EnhancedSkeleton className="h-10 w-48" />
          <EnhancedSkeleton className="h-64 w-full" />
        </div>
      </div>
    );
  }

  if (error || !block) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <p className="text-destructive">Failed to load block {height}</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Extract BlockMetadata transaction for additional info
  const blockMetaTxn = (block.transactions ?? []).find(
    isBlockMetadataTransactionResponse,
  ) as BlockMetadataTransactionResponse | undefined;

  const transactionCount =
    BigInt(block.last_version) - BigInt(block.first_version) + BigInt(1);

  const previousBlock = height > 0 ? (height - 1).toString() : null;
  const nextBlock = (height + 1).toString();

  return (
    <>
      <PageNavigation />
      <PageContainer>
        <Tabs
          value={currentTab}
          onValueChange={handleTabChange}
          className="w-full"
        >
          <TabsList variant="line" className="mb-6">
            <TabsTrigger value="overview" variant="line" className="gap-2">
              <BarChart3 className="h-4 w-4" />
              Overview
            </TabsTrigger>
            <TabsTrigger value="transactions" variant="line" className="gap-2">
              <FileText className="h-4 w-4" />
              Transactions
            </TabsTrigger>
          </TabsList>

          {/* Overview Tab */}
          <TabsContent value="overview">
            <Card>
              <CardContent className="pt-6">
                <ContentRow
                  title="Block Height:"
                  value={
                    <span className="font-mono text-lg">
                      {block.block_height}
                    </span>
                  }
                />
                <ContentRow
                  title={`Transactions (${transactionCount.toString()}):`}
                  value={
                    <div className="flex items-center gap-1">
                      <Link
                        href={`/txn/${block.first_version}`}
                        className="text-primary hover:underline font-mono"
                      >
                        {block.first_version}
                      </Link>
                      <span className="text-muted-foreground">-</span>
                      <Link
                        href={`/txn/${block.last_version}`}
                        className="text-primary hover:underline font-mono"
                      >
                        {block.last_version}
                      </Link>
                    </div>
                  }
                />
                <ContentRow
                  title="Timestamp:"
                  value={
                    <CopyableTimestamp timestamp={block.block_timestamp} />
                  }
                />
                {blockMetaTxn && (
                  <>
                    <ContentRow
                      title="Proposer:"
                      value={
                        <CopyableAddress
                          address={blockMetaTxn.proposer}
                          href={`/account/${blockMetaTxn.proposer}`}
                        />
                      }
                    />
                    <ContentRow title="Epoch:" value={blockMetaTxn.epoch} />
                    <ContentRow title="Round:" value={blockMetaTxn.round} />
                  </>
                )}
                {previousBlock && (
                  <ContentRow
                    title="Previous Block:"
                    value={
                      <Link
                        href={`/block/${previousBlock}`}
                        className="text-primary hover:underline font-mono"
                      >
                        {previousBlock}
                      </Link>
                    }
                  />
                )}
                <ContentRow
                  title="Next Block:"
                  value={
                    <Link
                      href={`/block/${nextBlock}`}
                      className="text-primary hover:underline font-mono"
                    >
                      {nextBlock}
                    </Link>
                  }
                />
              </CardContent>
            </Card>
          </TabsContent>

          {/* Transactions Tab */}
          <TabsContent value="transactions">
            {block.transactions && block.transactions.length > 0 ? (
              <div className="overflow-x-auto">
                <StyledTable>
                  <StyledTableHeader>
                    <StyledTableHeaderRow>
                      <StyledTableHead>Version</StyledTableHead>
                      <StyledTableHead className="flex items-center">
                        Type
                        <TransactionTypeTooltip />
                      </StyledTableHead>
                      <StyledTableHead>Hash</StyledTableHead>
                    </StyledTableHeaderRow>
                  </StyledTableHeader>
                  <TableBody>
                    {block.transactions.map((tx) => {
                      const version = "version" in tx ? tx.version : null;
                      return (
                        <TableRow key={tx.hash}>
                          <TableCell>
                            {version && (
                              <Link
                                href={`/txn/${version}`}
                                className="text-primary hover:underline font-mono"
                              >
                                {version}
                              </Link>
                            )}
                          </TableCell>
                          <TableCell>
                            <Badge variant="secondary">{tx.type}</Badge>
                          </TableCell>
                          <TableCell className="font-mono text-sm">
                            <Link
                              href={`/txn/${tx.hash}`}
                              className="text-primary hover:underline"
                            >
                              {tx.hash.slice(0, 10)}...{tx.hash.slice(-8)}
                            </Link>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </StyledTable>
              </div>
            ) : (
              <p className="text-muted-foreground text-center py-8">
                No transactions in this block
              </p>
            )}
          </TabsContent>
        </Tabs>
      </PageContainer>
    </>
  );
}
