"use client";

import PageNavigation from "@/components/layout/PageNavigation";
import { useQuery } from "@tanstack/react-query";
import { getTransactions, getLedgerInfo } from "@/services";
import { useGlobalStore } from "@/store/useGlobalStore";
import Link from "next/link";
import { Types } from "aptos";
import { useSearchParams, useRouter } from "next/navigation";
import { Suspense, useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  StyledTable,
  StyledTableHeader,
  StyledTableHeaderRow,
  StyledTableHead,
  TableBody,
  TableCell,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { useGetIsGraphqlClientSupported } from "@/hooks/common/useGraphqlClient";
import useGetUserTransactionVersions from "@/hooks/transactions/useGetUserTransactionVersions";
import { useGetTransaction } from "@/hooks/transactions/useGetTransaction";
import {
  getTransactionCounterparty,
  getTransactionAmount,
  getTransactionFunction,
  formatMoveAmount,
} from "@/utils/transaction";
import {
  FileText,
  ArrowRight,
  CheckCircle2,
  XCircle,
  Info,
  Rocket,
  User,
  Hourglass,
  Flag,
  StopCircle,
  HelpCircle,
  Loader2,
} from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { CopyableAddress } from "@/components/common/CopyableAddress";
import { formatAge, formatDateTimeUTC } from "@/utils/time";
import { cn } from "@/lib/utils";

const LIMIT = 20;
const NUM_PAGES = 100;

function formatTimestamp(timestamp: string): string {
  const date = new Date(parseInt(timestamp) / 1000);
  return date.toLocaleString();
}

function getTransactionType(tx: Types.Transaction): string {
  return tx.type
    .replace(/_/g, " ")
    .replace(/transaction$/, "")
    .trim();
}

function getSender(tx: Types.Transaction): string | null {
  if (tx.type === "user_transaction" && "sender" in tx) {
    return (tx as Types.UserTransaction).sender;
  }
  if (tx.type === "block_metadata_transaction" && "proposer" in tx) {
    return (tx as Types.BlockMetadataTransaction).proposer;
  }
  return null;
}

// Transaction Type definitions
enum TransactionTypeName {
  BlockMetadata = "block_metadata_transaction",
  Genesis = "genesis_transaction",
  User = "user_transaction",
  Pending = "pending_transaction",
  StateCheckpoint = "state_checkpoint_transaction",
  Validator = "validator_transaction",
  BlockEpilogue = "block_epilogue_transaction",
  Unknown = "unknown",
}

const TRANSACTION_TYPE_INFO: Record<
  TransactionTypeName,
  { label: string; description: string; icon: React.ReactNode }
> = {
  [TransactionTypeName.BlockMetadata]: {
    label: "Block Metadata",
    description:
      "System-generated transactions that provide additional data for each confirmed block.",
    icon: <FileText className="h-5 w-5" />,
  },
  [TransactionTypeName.Genesis]: {
    label: "Genesis Transaction",
    description: "The first transaction in the Movement blockchain.",
    icon: <Rocket className="h-5 w-5" />,
  },
  [TransactionTypeName.User]: {
    label: "User Transaction",
    description: "A transaction generated by users of the Movement blockchain.",
    icon: <User className="h-5 w-5" />,
  },
  [TransactionTypeName.Pending]: {
    label: "Pending Transaction",
    description:
      "A transaction currently in the mempool waiting to be committed.",
    icon: <Hourglass className="h-5 w-5" />,
  },
  [TransactionTypeName.StateCheckpoint]: {
    label: "State Checkpoint",
    description:
      "System-generated transactions that save the latest state of the Movement blockchain.",
    icon: <Flag className="h-5 w-5" />,
  },
  [TransactionTypeName.Validator]: {
    label: "Validator Transaction",
    description: "Validator metadata transactions.",
    icon: <CheckCircle2 className="h-5 w-5" />,
  },
  [TransactionTypeName.BlockEpilogue]: {
    label: "Block Epilogue Transaction",
    description: "Block epilogue transactions describing end state of a block.",
    icon: <StopCircle className="h-5 w-5" />,
  },
  [TransactionTypeName.Unknown]: {
    label: "Unknown",
    description: "Unknown transaction type.",
    icon: <HelpCircle className="h-5 w-5" />,
  },
};

function TransactionTypeTooltip() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="p-0.5 hover:bg-muted rounded transition-colors ml-1"
        title="View transaction types"
      >
        <Info className="h-4 w-4 text-muted-foreground" />
      </button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Transaction Types</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 max-h-[60vh] overflow-y-auto">
            {Object.values(TransactionTypeName).map((type) => {
              const info = TRANSACTION_TYPE_INFO[type];
              return (
                <div key={type} className="flex items-start gap-3">
                  <span className="text-muted-foreground mt-0.5">
                    {info.icon}
                  </span>
                  <div className="space-y-1">
                    <p className="font-medium text-sm">{info.label}</p>
                    <p className="text-xs text-muted-foreground">
                      {info.description}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

// User Transaction Row Component - fetches transaction details by version
function UserTransactionRow({
  version,
  timestampMode = "age",
  className,
}: {
  version: number;
  timestampMode?: "age" | "dateTime";
  className?: string;
}) {
  const {
    data: transaction,
    isError,
    isLoading,
  } = useGetTransaction(version.toString());

  if (isLoading) {
    return (
      <TableRow>
        <TableCell colSpan={8}>
          <Skeleton className="h-8 w-full" />
        </TableCell>
      </TableRow>
    );
  }

  if (!transaction || isError) {
    return null;
  }

  const status = "success" in transaction ? transaction.success : true;
  const sender = getSender(transaction);
  const timestamp = "timestamp" in transaction ? transaction.timestamp : null;
  const counterparty = getTransactionCounterparty(transaction);
  const amount = getTransactionAmount(transaction);
  const functionName = getTransactionFunction(transaction);
  const gasUsed = "gas_used" in transaction ? transaction.gas_used : null;
  const gasUnitPrice =
    "gas_unit_price" in transaction ? transaction.gas_unit_price : null;
  const txType = transaction.type as TransactionTypeName;
  const typeInfo =
    TRANSACTION_TYPE_INFO[txType] ??
    TRANSACTION_TYPE_INFO[TransactionTypeName.Unknown];

  return (
    <TableRow
      className={cn(
        "hover:bg-guild-green-500/10 group transition-colors border-b border-border/30 h-14",
        className,
      )}
    >
      {/* Transaction Hash + Status Icon */}
      <TableCell>
        <div className="flex items-center gap-2">
          {status ? (
            <CheckCircle2 className="h-4 w-4 text-guild-green-500 shrink-0" />
          ) : (
            <XCircle className="h-4 w-4 text-oracle-orange-500 shrink-0" />
          )}
          {transaction.hash ? (
            <CopyableAddress
              address={transaction.hash}
              href={`/txn/${transaction.hash}`}
              className="text-primary hover:underline font-mono group-hover:text-guild-green-500 transition-colors"
              truncateLength={{ start: 6, end: 6 }}
            />
          ) : (
            <span>-</span>
          )}
        </div>
      </TableCell>
      {/* Type with Icon */}
      <TableCell>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className="flex items-center gap-1.5 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors">
                {typeInfo.icon}
                <span className="text-xs font-medium capitalize">
                  {typeInfo.label}
                </span>
              </div>
            </TooltipTrigger>
            <TooltipContent>
              <p className="text-xs max-w-xs">{typeInfo.description}</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </TableCell>
      {/* Timestamp (Age/UTC) */}
      <TableCell className="text-muted-foreground text-sm group-hover:text-guild-green-500/90 transition-colors whitespace-nowrap">
        {timestamp
          ? timestampMode === "age"
            ? formatAge(timestamp)
            : formatDateTimeUTC(timestamp)
          : "-"}
      </TableCell>
      {/* Sender */}
      <TableCell>
        {sender ? (
          <CopyableAddress address={sender} href={`/account/${sender}`} />
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Receiver */}
      <TableCell className="hidden md:table-cell">
        {counterparty ? (
          <div className="flex items-center gap-1">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  {counterparty.role === "smartContract" ? (
                    <FileText className="h-4 w-4 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors" />
                  ) : (
                    <ArrowRight className="h-4 w-4 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors" />
                  )}
                </TooltipTrigger>
                <TooltipContent>
                  {counterparty.role === "smartContract"
                    ? "Smart Contract"
                    : "Receiver"}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <CopyableAddress
              address={counterparty.address}
              href={`/account/${counterparty.address}`}
            />
          </div>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Function */}
      <TableCell className="hidden sm:table-cell">
        {functionName ? (
          <code className="px-2 py-1 bg-muted rounded text-xs font-mono group-hover:bg-guild-green-500/20 group-hover:text-guild-green-500 transition-colors">
            {functionName}
          </code>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Amount */}
      <TableCell className="hidden lg:table-cell text-right">
        {amount !== undefined && amount > 0 ? (
          <span className="font-mono group-hover:text-guild-green-500 transition-colors">
            {formatMoveAmount(amount)} MOVE
          </span>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Gas */}
      <TableCell className="hidden lg:table-cell text-right">
        {gasUsed && gasUnitPrice ? (
          <span className="font-mono text-sm text-muted-foreground group-hover:text-guild-green-500/80 transition-colors">
            {formatMoveAmount(BigInt(gasUsed) * BigInt(gasUnitPrice))}
          </span>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
    </TableRow>
  );
}

// User Transactions Component
function UserTransactions() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const currentPage = parseInt(searchParams.get("page") ?? "1");
  const offset = (currentPage - 1) * LIMIT;

  // Timestamp display mode: "age" (default) or "dateTime"
  const [timestampMode, setTimestampMode] = useState<"age" | "dateTime">("age");

  const startVersion = useGetUserTransactionVersions(1)[0];
  const versions = useGetUserTransactionVersions(LIMIT, startVersion, offset);

  const isLoading = versions.length === 0;

  const handlePageChange = (page: number) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("type", "user");
    params.set("page", page.toString());
    router.push(`/transactions?${params.toString()}`);
  };

  // Generate page numbers to show
  const getVisiblePages = () => {
    const pages: (number | "ellipsis")[] = [];
    const showPages = 5;
    const halfShow = Math.floor(showPages / 2);

    let startPage = Math.max(1, currentPage - halfShow);
    let endPage = Math.min(NUM_PAGES, currentPage + halfShow);

    if (currentPage <= halfShow) {
      endPage = Math.min(NUM_PAGES, showPages);
    } else if (currentPage >= NUM_PAGES - halfShow) {
      startPage = Math.max(1, NUM_PAGES - showPages + 1);
    }

    if (startPage > 1) {
      pages.push(1);
      if (startPage > 2) pages.push("ellipsis");
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    if (endPage < NUM_PAGES) {
      if (endPage < NUM_PAGES - 1) pages.push("ellipsis");
      pages.push(NUM_PAGES);
    }

    return pages;
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
      <div className="overflow-x-auto">
        <StyledTable>
          <StyledTableHeader>
            <StyledTableHeaderRow>
              <StyledTableHead>Transaction Hash</StyledTableHead>
              <StyledTableHead className="flex items-center">
                Type
                <TransactionTypeTooltip />
              </StyledTableHead>
              <StyledTableHead>
                <div className="inline-flex items-center bg-muted/30 rounded-md p-0.5 border border-border/50">
                  <button
                    onClick={() => setTimestampMode("age")}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      timestampMode === "age"
                        ? "bg-guild-green-500 text-black shadow-sm"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    }`}
                  >
                    Age
                  </button>
                  <button
                    onClick={() => setTimestampMode("dateTime")}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      timestampMode === "dateTime"
                        ? "bg-guild-green-500 text-black shadow-sm"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    }`}
                  >
                    UTC
                  </button>
                </div>
              </StyledTableHead>
              <StyledTableHead>Sender</StyledTableHead>
              <StyledTableHead className="hidden md:table-cell">
                Receiver
              </StyledTableHead>
              <StyledTableHead className="hidden sm:table-cell">
                Function
              </StyledTableHead>
              <StyledTableHead className="hidden lg:table-cell text-right">
                Amount
              </StyledTableHead>
              <StyledTableHead className="hidden lg:table-cell text-right">
                Gas
              </StyledTableHead>
            </StyledTableHeaderRow>
          </StyledTableHeader>
          <TableBody>
            {versions.map((version) => (
              <UserTransactionRow
                key={version}
                version={version}
                timestampMode={timestampMode}
                className="animate-in slide-in-from-top-2 fade-in duration-500"
              />
            ))}
          </TableBody>
        </StyledTable>
      </div>

      {/* Pagination */}
      <div className="mt-6 flex justify-center">
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  if (currentPage > 1) handlePageChange(currentPage - 1);
                }}
                className={
                  currentPage === 1
                    ? "pointer-events-none opacity-50"
                    : "cursor-pointer"
                }
              />
            </PaginationItem>

            {getVisiblePages().map((page, i) =>
              page === "ellipsis" ? (
                <PaginationItem key={`ellipsis-${i}`}>
                  <PaginationEllipsis />
                </PaginationItem>
              ) : (
                <PaginationItem key={page}>
                  <PaginationLink
                    href="#"
                    onClick={(e) => {
                      e.preventDefault();
                      handlePageChange(page);
                    }}
                    isActive={page === currentPage}
                    className="cursor-pointer"
                  >
                    {page}
                  </PaginationLink>
                </PaginationItem>
              ),
            )}

            <PaginationItem>
              <PaginationNext
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  if (currentPage < NUM_PAGES)
                    handlePageChange(currentPage + 1);
                }}
                className={
                  currentPage === NUM_PAGES
                    ? "pointer-events-none opacity-50"
                    : "cursor-pointer"
                }
              />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </div>
    </>
  );
}

// All Transaction Row Component
function AllTransactionRow({
  transaction,
  timestampMode = "age",
  className,
}: {
  transaction: Types.Transaction;
  timestampMode?: "age" | "dateTime";
  className?: string;
}) {
  const status = "success" in transaction ? transaction.success : true;
  const sender = getSender(transaction);
  const version = "version" in transaction ? transaction.version : null;
  const timestamp = "timestamp" in transaction ? transaction.timestamp : null;
  const counterparty = getTransactionCounterparty(transaction);
  const amount = getTransactionAmount(transaction);
  const functionName = getTransactionFunction(transaction);
  const gasUsed = "gas_used" in transaction ? transaction.gas_used : null;
  const gasUnitPrice =
    "gas_unit_price" in transaction ? transaction.gas_unit_price : null;
  const txType = transaction.type as TransactionTypeName;
  const typeInfo =
    TRANSACTION_TYPE_INFO[txType] ??
    TRANSACTION_TYPE_INFO[TransactionTypeName.Unknown];

  return (
    <TableRow
      className={cn(
        "hover:bg-guild-green-500/10 group transition-colors border-b border-border/30 h-14",
        className,
      )}
    >
      {/* Version + Status Icon */}
      <TableCell>
        <div className="flex items-center gap-2">
          {status ? (
            <CheckCircle2 className="h-4 w-4 text-guild-green-500 shrink-0" />
          ) : (
            <XCircle className="h-4 w-4 text-oracle-orange-500 shrink-0" />
          )}
          {transaction.hash ? (
            <CopyableAddress
              address={transaction.hash}
              href={`/txn/${transaction.hash}`}
              className="text-primary hover:underline font-mono group-hover:text-guild-green-500 transition-colors"
              truncateLength={{ start: 6, end: 6 }}
            />
          ) : (
            <Link
              href={`/txn/${version}`}
              className="text-primary hover:underline font-mono group-hover:text-guild-green-500 transition-colors"
            >
              {version}
            </Link>
          )}
        </div>
      </TableCell>
      {/* Type with Icon */}
      <TableCell>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className="flex items-center gap-1.5 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors">
                {typeInfo.icon}
                <span className="text-xs font-medium capitalize">
                  {typeInfo.label}
                </span>
              </div>
            </TooltipTrigger>
            <TooltipContent>
              <p className="text-xs max-w-xs">{typeInfo.description}</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </TableCell>
      {/* Timestamp (Age/UTC) */}
      <TableCell className="text-muted-foreground text-sm group-hover:text-guild-green-500/90 transition-colors whitespace-nowrap">
        {timestamp
          ? timestampMode === "age"
            ? formatAge(timestamp)
            : formatDateTimeUTC(timestamp)
          : "-"}
      </TableCell>
      {/* Sender */}
      <TableCell>
        {sender ? (
          <CopyableAddress address={sender} href={`/account/${sender}`} />
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Receiver */}
      <TableCell className="hidden md:table-cell">
        {counterparty ? (
          <div className="flex items-center gap-1">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  {counterparty.role === "smartContract" ? (
                    <FileText className="h-4 w-4 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors" />
                  ) : (
                    <ArrowRight className="h-4 w-4 text-muted-foreground group-hover:text-guild-green-500/90 transition-colors" />
                  )}
                </TooltipTrigger>
                <TooltipContent>
                  {counterparty.role === "smartContract"
                    ? "Smart Contract"
                    : "Receiver"}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <CopyableAddress
              address={counterparty.address}
              href={`/account/${counterparty.address}`}
            />
          </div>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Function */}
      <TableCell className="hidden sm:table-cell">
        {functionName ? (
          <code className="px-2 py-1 bg-muted rounded text-xs font-mono group-hover:bg-guild-green-500/20 group-hover:text-guild-green-500 transition-colors">
            {functionName}
          </code>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Amount */}
      <TableCell className="hidden lg:table-cell text-right">
        {amount !== undefined && amount > 0 ? (
          <span className="font-mono group-hover:text-guild-green-500 transition-colors">
            {formatMoveAmount(amount)} MOVE
          </span>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
      {/* Gas */}
      <TableCell className="hidden lg:table-cell text-right">
        {gasUsed && gasUnitPrice ? (
          <span className="font-mono text-sm text-muted-foreground group-hover:text-guild-green-500/80 transition-colors">
            {formatMoveAmount(BigInt(gasUsed) * BigInt(gasUnitPrice))}
          </span>
        ) : (
          <span className="text-muted-foreground group-hover:text-guild-green-500/70 transition-colors">
            -
          </span>
        )}
      </TableCell>
    </TableRow>
  );
}

// All Transactions Component
function AllTransactions() {
  const { aptos_client, network_value } = useGlobalStore();
  const searchParams = useSearchParams();
  const router = useRouter();

  // Timestamp display mode: "age" (default) or "dateTime"
  const [timestampMode, setTimestampMode] = useState<"age" | "dateTime">("age");

  const startParam = searchParams.get("start");

  // Fetch ledger info to get max version
  const { data: ledgerInfo } = useQuery({
    queryKey: ["ledgerInfo", network_value],
    queryFn: () => getLedgerInfo(aptos_client),
  });

  const maxVersion = ledgerInfo ? parseInt(ledgerInfo.ledger_version) : 0;
  const maxStart = Math.max(0, maxVersion - LIMIT + 1);

  // Calculate start position
  let start = maxStart;
  if (startParam !== null) {
    start = Math.min(Math.max(0, parseInt(startParam)), maxStart);
  }

  // Fetch transactions
  const { data: transactions, isLoading } = useQuery({
    queryKey: ["transactions", { start, limit: LIMIT }, network_value],
    queryFn: () => getTransactions({ start, limit: LIMIT }, aptos_client),
    enabled: maxVersion > 0,
  });

  // Pagination calculations
  const totalPages = Math.ceil(maxVersion / LIMIT);
  const currentPage = Math.max(1, Math.ceil((maxVersion - start) / LIMIT));

  const handlePageChange = (page: number) => {
    const newStart = Math.max(0, maxVersion - page * LIMIT + 1);
    const params = new URLSearchParams(searchParams.toString());
    params.set("type", "all");
    params.set("start", newStart.toString());
    router.push(`/transactions?${params.toString()}`);
  };

  // Generate page numbers to show
  const getVisiblePages = () => {
    const pages: (number | "ellipsis")[] = [];
    const showPages = 5;
    const halfShow = Math.floor(showPages / 2);

    let startPage = Math.max(1, currentPage - halfShow);
    let endPage = Math.min(totalPages, currentPage + halfShow);

    if (currentPage <= halfShow) {
      endPage = Math.min(totalPages, showPages);
    } else if (currentPage >= totalPages - halfShow) {
      startPage = Math.max(1, totalPages - showPages + 1);
    }

    if (startPage > 1) {
      pages.push(1);
      if (startPage > 2) pages.push("ellipsis");
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    if (endPage < totalPages) {
      if (endPage < totalPages - 1) pages.push("ellipsis");
      pages.push(totalPages);
    }

    return pages;
  };

  if (isLoading || !transactions) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
      <div className="overflow-x-auto">
        <StyledTable>
          <StyledTableHeader>
            <StyledTableHeaderRow>
              <StyledTableHead>Version</StyledTableHead>
              <StyledTableHead className="flex items-center">
                Type
                <TransactionTypeTooltip />
              </StyledTableHead>
              <StyledTableHead>
                <div className="inline-flex items-center bg-muted/30 rounded-md p-0.5 border border-border/50">
                  <button
                    onClick={() => setTimestampMode("age")}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      timestampMode === "age"
                        ? "bg-guild-green-500 text-black shadow-sm"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    }`}
                  >
                    Age
                  </button>
                  <button
                    onClick={() => setTimestampMode("dateTime")}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      timestampMode === "dateTime"
                        ? "bg-guild-green-500 text-black shadow-sm"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    }`}
                  >
                    UTC
                  </button>
                </div>
              </StyledTableHead>
              <StyledTableHead>Sender</StyledTableHead>
              <StyledTableHead className="hidden md:table-cell">
                Receiver
              </StyledTableHead>
              <StyledTableHead className="hidden sm:table-cell">
                Function
              </StyledTableHead>
              <StyledTableHead className="hidden lg:table-cell text-right">
                Amount
              </StyledTableHead>
              <StyledTableHead className="hidden lg:table-cell text-right">
                Gas
              </StyledTableHead>
            </StyledTableHeaderRow>
          </StyledTableHeader>
          <TableBody>
            {transactions.map((tx: Types.Transaction) => (
              <AllTransactionRow
                key={tx.hash}
                transaction={tx}
                timestampMode={timestampMode}
                className="animate-in slide-in-from-top-2 fade-in duration-500"
              />
            ))}
          </TableBody>
        </StyledTable>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="mt-6 flex justify-center">
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (currentPage > 1) handlePageChange(currentPage - 1);
                  }}
                  className={
                    currentPage === 1
                      ? "pointer-events-none opacity-50"
                      : "cursor-pointer"
                  }
                />
              </PaginationItem>

              {getVisiblePages().map((page, i) =>
                page === "ellipsis" ? (
                  <PaginationItem key={`ellipsis-${i}`}>
                    <PaginationEllipsis />
                  </PaginationItem>
                ) : (
                  <PaginationItem key={page}>
                    <PaginationLink
                      href="#"
                      onClick={(e) => {
                        e.preventDefault();
                        handlePageChange(page);
                      }}
                      isActive={page === currentPage}
                      className="cursor-pointer"
                    >
                      {page}
                    </PaginationLink>
                  </PaginationItem>
                ),
              )}

              <PaginationItem>
                <PaginationNext
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    if (currentPage < totalPages)
                      handlePageChange(currentPage + 1);
                  }}
                  className={
                    currentPage === totalPages
                      ? "pointer-events-none opacity-50"
                      : "cursor-pointer"
                  }
                />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      )}
    </>
  );
}

function TransactionsContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const isGraphqlClientSupported = useGetIsGraphqlClientSupported();

  // Determine the initial type based on URL or graphql support
  const typeParam = searchParams.get("type");
  const [isUserTransactions, setIsUserTransactions] = useState<boolean | null>(
    null,
  );

  // Set initial type on mount
  useEffect(() => {
    if (typeParam === "all") {
      setIsUserTransactions(false);
    } else if (typeParam === "user") {
      setIsUserTransactions(true);
    } else {
      // Default based on graphql support
      setIsUserTransactions(isGraphqlClientSupported);
      // Update URL to reflect the default
      const params = new URLSearchParams(searchParams.toString());
      params.set("type", isGraphqlClientSupported ? "user" : "all");
      router.replace(`/transactions?${params.toString()}`);
    }
  }, [typeParam, isGraphqlClientSupported, router, searchParams]);

  const toggleTransactionType = () => {
    const params = new URLSearchParams();
    if (isUserTransactions) {
      params.set("type", "all");
    } else {
      params.set("type", "user");
    }
    router.push(`/transactions?${params.toString()}`);
    setIsUserTransactions(!isUserTransactions);
  };

  // Show loading while determining the type
  if (isUserTransactions === null) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-row justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">
          {isUserTransactions ? "User Transactions" : "All Transactions"}
        </h1>
        {isGraphqlClientSupported && (
          <Button variant="ghost" onClick={toggleTransactionType}>
            {isUserTransactions
              ? "View All Transactions"
              : "View User Transactions"}
          </Button>
        )}
      </div>

      {isUserTransactions ? <UserTransactions /> : <AllTransactions />}
    </>
  );
}

export default function TransactionsPage() {
  return (
    <>
      <PageNavigation title="Transactions" />
      <div className="container mx-auto px-4 py-8">
        <Suspense
          fallback={
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          }
        >
          <TransactionsContent />
        </Suspense>
      </div>
    </>
  );
}
